const placasDeVideo = [
    {
      id: "001",
      fabricante: "NVIDIA",
      marca: "Palit",
      modelo: "RTX 2060 SUPER",
      memoria: "8 GB",
      precio: "$246999",
    },
    {
      id: "002",
      fabricante: "NVIDIA",
      marca: "Nvidia",
      modelo: "RTX 3070",
      memoria: "8 GB",
      precio: "$350999",
    },
    {
      id: "003",
      fabricante: "NVIDIA",
      marca: "MSI",
      modelo: "RTX 3080",
      memoria: "10 GB",
      precio: "$624999",
    },
    {
      id: "004",
      fabricante: "NVIDIA",
      marca: "Nvidia",
      modelo: "RTX 3090",
      memoria: "24 GB",
      precio: "$739999",
    },
    {
      id: "005",
      fabricante: "NVIDIA",
      marca: "Nvidia",
      modelo: "RTX 3090",
      memoria: "24 GB",
      precio: "$864749",
    },
    {
      id: "006",
      fabricante: "NVIDIA",
      marca: "Asus",
      modelo: "RTX 4070",
      memoria: "12 GB",
      precio: "$755959",
    },
    {
      id: "007",
      fabricante: "NVIDIA",
      marca: "MSI",
      modelo: "RTX 4080",
      memoria: "16 GB",
      precio: "$1055647",
    },
    {
      id: "008",
      fabricante: "AMD",
      marca: "AMD",
      modelo: "RX 580",
      memoria: "8 GB",
      precio: "$232999",
    },
    {
      id: "009",
      fabricante: "AMD",
      marca: "PowerColor",
      modelo: "RX 6500 XT",
      memoria: "4 GB",
      precio: "$169423",
    },
    {
      id: "010",
      fabricante: "AMD",
      marca: "Sapphire",
      modelo: "RX 6700 XT",
      memoria: "12 GB",
      precio: "$269999",
    },
    {
      id: "011",
      fabricante: "AMD",
      marca: "ASRock",
      modelo: "RX 6800 XT",
      memoria: "16 GB",
      precio: "$574999",
    },
    {
      id: "012",
      fabricante: "AMD",
      marca: "ASRock",
      modelo: "RX 6900 XT",
      memoria: "16 GB",
      precio: "$407019",
    },
    {
      id: "013",
      fabricante: "AMD",
      marca: "ASRock",
      modelo: "RX 6900 XT",
      memoria: "16 GB",
      precio: "$440889",
    },
    {
      id: "014",
      fabricante: "Asus",
      marca: "Asus",
      modelo: "ROG-STRIX-RTX4080-O16G-GAMING",
      memoria: "16 GB",
      precio: "$1758102",
    },
    {
      id: "015",
      fabricante: "Asus",
      marca: "Asus",
      modelo: "ROG-STRIX-RTX4080-O16G-GAMING",
      memoria: "16 GB",
      precio: "$2296302",
    },
  ];